// AUTH
export const REGISTER_USER = 'REGISTER_USER'
export const DELETE_AUTH_ERROR_MESSAGE = 'DELETE_AUTH_ERROR_MESSAGE'
export const SET_AUTH_IS_LOADING = 'SET_AUTH_IS_LOADING'
export const SET_USER_IS_JUST_REGISTERED = 'SET_USER_IS_JUST_REGISTERED'
export const SIGN_IN_USER = 'SIGN_IN_USER'

// MAIN
export const MAIN_LOADER_HANDLER = 'MAIN_LOADER_HANDLER'
export const DELETE_MAIN_ERROR_MESSAGE = 'DELETE_MAIN_ERROR_MESSAGE'
export const SET_RECOMMENDATION_PAGE_DATA = 'SET_RECOMMENDATION_PAGE_DATA'

// PLAYER
export const SET_PLAYER_GROUP = 'SET_PLAYER_GROUP'
export const SET_PLAYER_TRACK_INDEX = 'SET_PLAYER_TRACK_INDEX'
export const SET_PLAYER_TRACK_TIME_POSITION = 'SET_PLAYER_TRACK_TIME_POSITION'
export const SET_PLAYER_IS_LOADING = 'SET_PLAYER_IS_LOADING'
export const SET_PLAYER_IS_PLAYING = 'SET_PLAYER_IS_PLAYING'
export const DELETE_PLAYER_ERROR_MESSAGE = 'DELETE_PLAYER_ERROR_MESSAGE'
export const SET_PLAYER_VOLUME = 'SET_PLAYER_VOLUME'
