// AUTH
export const REGISTER_USER = 'REGISTER_USER'
export const DELETE_AUTH_ERROR_MESSAGE = 'DELETE_AUTH_ERROR_MESSAGE'
export const SET_AUTH_IS_LOADING = 'SET_AUTH_IS_LOADING'
export const SET_USER_IS_JUST_REGISTERED = 'SET_USER_IS_JUST_REGISTERED'
export const SIGN_IN_USER = 'SIGN_IN_USER'
export const UPDATE_USER = 'UPDATE_USER'

// MAIN
export const SET_MAIN_RECOMENDATION_IS_LOADING = 'SET_MAIN_RECOMENDATION_IS_LOADING'
export const SET_MAIN_GENRES_IS_LOADING = 'SET_MAIN_GENRES_IS_LOADING'
export const SET_MAIN_GENRES_IS_LOADING_OBSERVER = 'SET_MAIN_GENRES_IS_LOADING_OBSERVER'
export const SET_MAIN_MY_LISTS_IS_LOADING = 'SET_MAIN_MY_LISTS_IS_LOADING'
export const SET_MAIN_SEARCH_IS_LOADING = 'SET_MAIN_SEARCH_IS_LOADING'
export const SET_MAIN_ERROR_MESSAGE = 'SET_MAIN_ERROR_MESSAGE'
export const SET_MAIN_RECOMMENDATION_PAGE_DATA = 'SET_MAIN_RECOMMENDATION_PAGE_DATA'
export const SET_MAIN_GENRES_PLAYLISTS = 'SET_GENRES_PLAYLISTS'
export const SET_MAIN_GENRES_PLAYLISTS_INDEX = 'SET_MAIN_GENRES_PLAYLISTS_INDEX'
export const SET_MAIN_IS_CREATING_PLAYLIST = 'SET_MAIN_IS_CREATING_PLAYLIST'
export const SET_MAIN_PLAYLIST_FORM_INPUT_VALUE = 'SET_MAIN_PLAYLIST_FORM_INPUT_VALUE'
export const SET_MAIN_PLAYLIST_FORM_TEXT_AREA_VALUE = 'SET_MAIN_PLAYLIST_FORM_TEXT_AREA_VALUE'
export const SET_MAIN_PLAYLIST_FORM_IMG_SRC = 'SET_MAIN_PLAYLIST_FORM_IMG_SRC'
export const SET_MAIN_SEARCH_VALUE = 'SET_MAIN_SEARCH_VALUE'
export const SET_MAIN_SEARCH_RESULTS = 'SET_MAIN_SEARCH_RESULTS'

// PLAYER
export const SET_PLAYER_GROUP = 'SET_PLAYER_GROUP'
export const SET_PLAYER_TRACK_INDEX = 'SET_PLAYER_TRACK_INDEX'
export const SET_PLAYER_TRACK_TIME_POSITION = 'SET_PLAYER_TRACK_TIME_POSITION'
export const SET_PLAYER_IS_LOADING = 'SET_PLAYER_IS_LOADING'
export const SET_PLAYER_IS_PLAYING = 'SET_PLAYER_IS_PLAYING'
export const DELETE_PLAYER_ERROR_MESSAGE = 'DELETE_PLAYER_ERROR_MESSAGE'
export const SET_PLAYER_VOLUME = 'SET_PLAYER_VOLUME'
export const SET_SONG_IS_IN_FAVORITES = 'SET_SONG_IS_IN_FAVORITES'

// USER
export const SET_USER_ERROR_MESSAGE = 'SET_USER_ERROR_MESSAGE'
